# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Python app to Azure Web App - infraexcel

on:
  push:
    branches:
      - dependabot/pip/flask-1.0

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up Python version
      uses: actions/setup-python@v1
      with:
        python-version: '3.6'

    - name: Build using AppService-Build
      uses: azure/appservice-build@v1
      with:
        platform: python

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v1
      with:
        app-name: 'infraexcel'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_3dad45d2ad044e76b4be50dd746ddb5e }}